import "server-only";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

/**
 * FileStore port (ARCHITECTURE.md D9). The database stores metadata and a storage key; bytes
 * live here. Local disk in development; Azure Blob Storage (Canada Central) and SharePoint
 * document libraries for offer letters plug in behind the same interface.
 */
export interface FileStore {
  readonly kind: "local" | "azure-blob" | "sharepoint";
  put(key: string, bytes: Buffer, contentType: string): Promise<void>;
  get(key: string): Promise<Buffer>;
  remove(key: string): Promise<void>;
}

/** Keys are generated by PATS (uuid-based); reject anything that could escape the root. */
function safeKey(key: string) {
  if (!/^[a-z0-9][a-z0-9/_.-]*$/i.test(key) || key.includes("..")) throw new Error(`Invalid storage key: ${key}`);
  return key;
}

function localStore(root: string): FileStore {
  const full = (key: string) => path.join(root, safeKey(key));
  return {
    kind: "local",
    async put(key, bytes) {
      await mkdir(path.dirname(full(key)), { recursive: true });
      await writeFile(full(key), bytes);
    },
    get: (key) => readFile(full(key)),
    async remove(key) {
      await rm(full(key), { force: true });
    },
  };
}

let store: FileStore | null = null;

export function fileStore(): FileStore {
  store ??= localStore(path.resolve(process.env.FILE_STORE_DIR ?? ".storage"));
  return store;
}
